---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    maxNoOfPodsToEvictPerNode: 5 # default 2
    strategies:
      "RemoveDuplicates":
         enabled: true
      "RemovePodsViolatingInterPodAntiAffinity":
         enabled: true
      "LowNodeUtilization":
         enabled: true
         params:
           thresholdPriority: 1000
           nodeResourceUtilizationThresholds:
             thresholds:
               "cpu" : 20
               "memory": 20
               "pods": 20
             targetThresholds:
               "cpu" : 70
               "memory": 70
               "pods": 90
      "LowNodeActualUtilization":
         enabled: true
         params:
           thresholdPriority: 1000
           nodeResourceActualUtilizationThresholds:
             thresholds:
               "cpu" : 30
               "memory": 30
             targetThresholds:
               "cpu" : 60
               "memory": 60