---
apiVersion: v1
kind: ConfigMap
metadata:
  name: descheduler-policy-configmap
  namespace: kube-system
data:
  policy.yaml: |
    apiVersion: "descheduler/v1alpha1"
    kind: "DeschedulerPolicy"
    maxNoOfPodsToEvictPerNode: 1 # default 1
    strategies:
      "RemoveDuplicates":
         enabled: true
      "RemovePodsViolatingInterPodAntiAffinity":
         enabled: true
      "LowNodeUtilization":
         enabled: true
         params:
           #thresholdPriority: 1000
           nodeResourceUtilizationThresholds:
             thresholds:
               "cpu" : 20
               "memory": 20
               "pods": 20
             targetThresholds:
               "cpu" : 80
               "memory": 80
               "pods": 80
      "LowNodeActualUtilization":
         enabled: true
         params:
           thresholdPriority: 1000
           nodeResourceActualUtilizationThresholds:
             limitNumberOfTargetNodes: 1 # default 1
             excludeOwnerKinds:
             - "Cronjob"
             - "Job"
             thresholds:
               "cpu" : 30
               "memory": 30
             targetThresholds:
               "cpu" : 70
               "memory": 70